### ISSUE TITLE
Exp máximo de 3.500

### ISSUE THREAD

**Issue by verwischt** [SamueldaCostaAraujoNunes/ValorantPassBattle#3]
Não consigo colocar meu exp atual no passe. Diz que o máximo é 3.500. Lembro que numa das versões anteriores ao re-upload por causa da derrubada do app na Playstore tive o mesmo problema, mas tinha sido corrigido. Agora o erro voltou.

![Screenshot_20210913-211221.png](https://user-images.githubusercontent.com/83430291/133173246-f0aaf60a-9480-440a-ba07-67cb5f91d15b.png)

**Comment by SamueldaCostaAraujoNunes** [comment]
Opa!! Rapaz, verifiquei aqui e o limite está certo! O passe funciona da seguinte forma. A primeira recompensa tem um custo de 0 EXP, a segunda tem 2000 EXP, e a partir da 3a em diante, a quantidade de EXP aumenta 750 EXP por nível. 

Por exemplo:
![image](https://user-images.githubusercontent.com/66431643/133173950-d25325c1-7cb3-4c61-9f02-232656a0a022.png)

O tier 12, seria basicamente 2000 + ( 12 - 2 ) * 750 => 2000 + 7500 => 9500.

Para o tier 4, que vc está no momento. seria 2000 + ( 4 - 2 )*750 => 2000 + 1500 => 3500.

Por isso esse limite. Se vc puder verificar se a quantidade no vava ta 9785 mesmo, me manda um print do jogo pfvr. Que eu dou uma estuda e se tiver algum bug, eu corrijo ainda esta semana!!

Valeu pelo feedback!

**Comment by verwischt** [comment]
Ah! Tô me sentindo um idiota agora. Kkkkkk Mil desculpas pela pergunta besta. Me confundi total. Não consigo enviar print do valorant agora, pois estou logado no meu linux. Mas relaxa que foi erro meu, desatenção minha.

**Comment by verwischt** [comment]
Valeu pelo app, cara. Mt foda!
