### ISSUE TITLE
Update? 

### ISSUE THREAD

**Issue by Karuneko** [SamueldaCostaAraujoNunes/ValorantPassBattle#4]
It's been almost a whole 2 acts since the app was the latest Battlepass, any plans for an update??

This app was really useful to use on the go for me.

**Comment by SamueldaCostaAraujoNunes** [comment]
Unfortunately, I'm not having time to update the pass information. The tier scoring mechanic is quite unstable, so I kept doing maintenance and it didn't become profitable. Anyway, thanks for the appreciation, the project is open for changes and extensions
